### ISSUE TITLE
Playing Again Issue

### ISSUE THREAD

**Issue by BoshEee** [WebAhead8/snakes-and-ladders#10]
when we start a new game (play again) the previous moves stays at the board

**Comment by AladdinHammodi** [comment]
when you click on play again it should take you to the main screen

**Comment by BoshEee** [comment]
Yes, it takes us to the main screen but if you then click start game, the black squares from the previous game stays at the board. which if we did not finished the game and click play again it will continue from the previous moves not starting a new one

**Comment by AladdinHammodi** [comment]
this issue is fixed now 
try to clone the updated version
