### ISSUE TITLE
All the commits were made by 1 person

### ISSUE THREAD

**Issue by shiryz** [WebAhead8/snakes-and-ladders#3]
Is there a reason why all the commits were made by @AladdinHammodi?

@mohamadsawaed , @ShabJdeed  what happened?

![image](https://user-images.githubusercontent.com/22002193/103867762-8f263e80-50d0-11eb-91f2-dcf6d8eeb7cf.png)

**Comment by AladdinHammodi** [comment]
we will explain it to you in person
