### ISSUE TITLE
The player block(Square) move

### ISSUE THREAD

**Issue by BoshEee** [WebAhead8/snakes-and-ladders#8]
when we made the second move the previous move stays at the 
board. It's make it hard to know where we are currently at.

**Comment by AladdinHammodi** [comment]
this is a beta version as we mentioned in the readme 
a few changes still have to be done 
we are aware of this issue 
thas why we used the alert of current possition
but thanks any way

**Comment by AladdinHammodi** [comment]
this issue is fixed
